variance_filter_thres = 0.1
data_path = '/home/gyli/GP_HP/data/hypertension.csv'
gamma = [2e-5, 2e-4, 2e-3, 2e-2, 2e-1, 1, 2, 20, 200]
C = [1e-3, 1e-2, 1e-1, 1.0, 10.0, 100.0]
# gamma = [2e-9, 2e-8]
# C = [1e-3, 1e-2]